#include "keymap_common.h"

const uint8_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
[0] = KEYMAP(ESC, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, MINS,EQL, BSLS, GRV, \
TAB, Q, W, E, R, T, Y, U, I, O, P, LBRC, RBRC, BSPC, \
LCTL, A, S, D, F, G, H, J, K, L, SCLN, QUOT, ENT,
LSFT, Z, X, C, V, B, N, M, COMM,DOT, SLSH, RSFT, FN0, \
NO, LALT, LGUI, SPC, RGUI, RALT, NO, NO),

[1] = KEYMAP(PWR, F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, F12, INS, DEL, \
CAPS, TRNS, UP, TRNS, TRNS, TRNS, TRNS, TRNS, PSCR, SLCK, PAUS, UP, TRNS,  BSPC, \
TRNS, LEFT, DOWN, RIGHT, TRNS, TRNS, PAST, PSLS, HOME, PGUP, LEFT, RGHT, PENT, \
TRNS, TRNS, TRNS, TRNS, TRNS, TRNS, PPLS, PMNS,END, PGDN, DOWN, TRNS, TRNS,  \
TRNS, TRNS, TRNS,  TRNS,  TRNS, TRNS, TRNS, TRNS),
};

const uint16_t PROGMEM fn_actions[] = {
	[0] = ACTION_LAYER_MOMENTARY(1),
};

